package deploy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

const flyTomlTmpl = `# Fly.io config - generated by nimbus deploy
app = "{{.AppName}}"
primary_region = "{{.Region}}"

[build]
  [build.args]
    GO_VERSION = "{{.GoVersion}}"

[env]
  PORT = "8080"
  APP_ENV = "production"

{{if .RunMigrations}}
[deploy]
  release_command = "./server migrate"
{{end}}

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
`

func deployFly(dir string, cfg *Config) error {
	appName := cfg.AppName
	if appName == "" {
		appName = filepath.Base(dir)
	}
	region := cfg.Region
	if region == "" {
		region = "iad"
	}

	// Ensure fly.toml exists
	flyPath := filepath.Join(dir, "fly.toml")
	runMigrations := cfg.Migrations == nil || (cfg.Migrations != nil && *cfg.Migrations)
	if _, err := os.Stat(flyPath); os.IsNotExist(err) {
		t := template.Must(template.New("fly").Parse(flyTomlTmpl))
		f, err := os.Create(flyPath)
		if err != nil {
			return err
		}
		goVer := DetectGoVersion(dir)
		_ = t.Execute(f, map[string]any{
			"AppName":        appName,
			"Region":         region,
			"GoVersion":      goVer,
			"RunMigrations":  runMigrations,
		})
		_ = f.Close()
		fmt.Println("  Created fly.toml")
	}

	// Run fly deploy
	fmt.Println("  Deploying to Fly.io...")
	cmd := exec.Command("fly", "deploy", "--yes")
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = append(os.Environ(), "FLY_APP="+appName)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("fly deploy failed: %w\n  Ensure flyctl is installed: https://fly.io/docs/flyctl/install/", err)
	}

	fmt.Println("  Deployed! Run: fly open")
	return nil
}
