package deploy

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
)

func deployRender(dir string, cfg *Config) error {
	// Require render CLI
	if err := requireCLI("render"); err != nil {
		return err
	}

	// Verify authentication
	check := exec.Command("render", "config")
	check.Stdout = io.Discard
	check.Stderr = io.Discard
	if err := check.Run(); err != nil {
		fmt.Println("  Render CLI not authenticated. Please run 'render config' to set your API key first or use the browser to deploy.")
		// We still attempt to deploy as it might be an issue with `render config` working differently
	}

	serviceName := cfg.Service
	if serviceName == "" {
		serviceName = cfg.AppName
	}
	if serviceName == "" {
		serviceName = filepath.Base(dir)
	}

	// Ensure render.yaml exists
	if err := ensureRenderYaml(dir, cfg, serviceName); err != nil {
		return err
	}

	fmt.Println("  Deploying to Render via render.yaml blueprint...")

	// The render CLI uses blueprints to deploy apps automatically from the render.yaml
	// `render blueprint apply` requires the service to be connected via git.
	// Since Render is primarily GitOps-driven, we just remind the user to push code.

	fmt.Printf("\n  ✅ Render configuration created!\n")
	fmt.Printf("  Render is a GitOps platform. To deploy %s:\n", serviceName)
	fmt.Println("  1. git add render.yaml && git commit -m \"Add Render config\"")
	fmt.Println("  2. git push")
	fmt.Println("  3. Navigate to https://dashboard.render.com/blueprints and connect this repository.")

	return nil
}

func ensureRenderYaml(dir string, cfg *Config, serviceName string) error {
	path := filepath.Join(dir, "render.yaml")
	if _, err := os.Stat(path); err == nil {
		// already exists
		return nil
	}

	runMigrations := cfg.Migrations == nil || (cfg.Migrations != nil && *cfg.Migrations)
	buildCommand := "go build -o server ."
	startCommand := "./server"

	if runMigrations {
		startCommand = "./server migrate && ./server"
	}

	var buf bytes.Buffer
	buf.WriteString("services:\n")
	buf.WriteString(fmt.Sprintf("  - type: web\n"))
	buf.WriteString(fmt.Sprintf("    name: %s\n", serviceName))
	buf.WriteString(fmt.Sprintf("    env: docker\n"))

	// If using docker, we specify docker env, but render can also use Go native
	// We'll use docker since Nimbus expects a Dockerfile.
	if _, err := os.Stat(filepath.Join(dir, "Dockerfile")); err == nil {
		buf.WriteString("    # Uses the existing Dockerfile generated by Nimbus\n")
		buf.WriteString("    autoDeploy: true\n")
		// if migrate we need a release command
		if runMigrations {
			buf.WriteString("    envVars:\n")
			buf.WriteString("      - key: PORT\n")
			buf.WriteString("        value: 8080\n")
		}
	} else {
		buf.WriteString(fmt.Sprintf("    env: go\n"))
		buf.WriteString(fmt.Sprintf("    buildCommand: \"%s\"\n", buildCommand))
		buf.WriteString(fmt.Sprintf("    startCommand: \"%s\"\n", startCommand))
	}

	if err := os.WriteFile(path, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write render.yaml: %w", err)
	}
	fmt.Println("  Created render.yaml blueprint")
	return nil
}
